### ISSUE TITLE
Passing boolean value in predicate raises AttributeError

### ISSUE THREAD

**Issue by dfrank-a** [AlexHill/django-relativity#19]
I have the following `Relationship` defined in my project:

`active_offer = Relationship(
      to="pricing.Offer",
      predicate=Q(
          deleted=False, product_id=L("product_id"), offer_target=L("offer_target")
      ),
      multiple=False,
  )'
  
  After upgrading to 0.2.4 from 0.2.1, this definition raises an AttributeError. Wrapping False in a call to `django.db.models.Value` seems to fix it. 
  
  Attached is a traceback of the error I encountered
  
[relativity_traceback.txt](https://github.com/AlexHill/django-relativity/files/7288041/relativity_traceback.txt)

**Comment by AlexHill** [comment]
Fixed in #20. Will release 0.2.5 shortly.

**Comment by AlexHill** [comment]
0.2.5 has been published to PyPI and should fix your issue. Let me know how you go!
